[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge/=lib/forge-std/src/"
]

fs_permissions = [{ access = "read-write", path = "./deployments/"}]

solc = "0.8.28"
evm_version = "berlin"
optimizer = true
optimizer_runs = 1
bytecode_hash = "none"
cbor_metadata = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
