[package]
name = "notary-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.12.1", features = ["sol-types", "contract"] }
serde = { version = "1.0.214", features = ["derive"] }