[package]
name = "voting-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0.24", features = ["sol-types", "contract"] }
serde = { version = "1.0", features = ["derive"] }