[package]
name = "pod-solidity-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["sol-types", "contract"] }
serde = { version = "1.0.214", features = ["derive"] }