//! Structure-aware fuzzing of `Receipt`: serde round-trips (JSON + bincode)
//! and merkleization — every log proof / multiproof a receipt hands out must
//! verify against its own merkle root.
#![no_main]

use bincode::config::standard;
use libfuzzer_sys::fuzz_target;
use pod_types::{
    Hashable, Merkleizable, Receipt,
    cryptography::merkle_tree::{StandardMerkleTree, index_prefix},
};

fuzz_target!(|receipt: Receipt| {
    // Serde round-trips.
    let json = serde_json::to_string(&receipt).expect("JSON serialization must succeed");
    let from_json: Receipt = serde_json::from_str(&json).expect("own JSON must deserialize");
    assert_eq!(receipt, from_json);

    let bytes = bincode::serde::encode_to_vec(&receipt, standard()).expect("bincode encode");
    let (from_bin, _): (Receipt, usize) =
        bincode::serde::decode_from_slice(&bytes, standard()).expect("own bincode must decode");
    assert_eq!(receipt, from_bin);

    // Merkleization: proofs generated by the receipt verify against its root.
    let tree = receipt.to_merkle_tree();
    let root = tree.root();

    for (i, log) in receipt.logs.iter().enumerate() {
        let proof = receipt
            .generate_proof_for_log_hash(i)
            .expect("log index is in range");
        let leaf = StandardMerkleTree::hash_leaf(&index_prefix("log_hashes", i), log.hash_custom());
        assert!(
            StandardMerkleTree::verify_proof(root, leaf, proof),
            "log hash proof must verify"
        );

        let (leaves, proof) = receipt
            .generate_multi_proof_for_log(i)
            .expect("log index is in range");
        assert!(
            StandardMerkleTree::verify_multi_proof(root, &leaves, proof),
            "per-log multiproof must verify"
        );
    }

    let (leaves, proof) = receipt.generate_multi_proof_for_log_hashes();
    assert!(
        StandardMerkleTree::verify_multi_proof(root, &leaves, proof),
        "log-hashes multiproof must verify"
    );

    let (leaves, proof) = receipt.generate_multi_proof_for_logs();
    assert!(
        StandardMerkleTree::verify_multi_proof(root, &leaves, proof),
        "all-logs multiproof must verify"
    );
});
