generate:
	forge bind --crate-name voting-bindings --bindings-path ../bindings --alloy-version 2.0.4 --force --no-metadata --select "^Voting$$" --overwrite

check:
	forge bind --crate-name voting-bindings --bindings-path ../bindings --alloy-version 2.0.4 --force --no-metadata --select "^Voting$$"

.PHONY: generate
.PHONY: check
