[package]
name = "optimism-tx-auction"
version = "0.1.0"
edition = "2024"

[dependencies]
pod-sdk = { path = "../../rust-sdk" }
pod-types = { path = "../../types" }

alloy = { version = "1.0.9", features = ["sol-types", "contract"] }
op-alloy = { version = "0.18.14", features = ["full"] }
tracing = "0.1.41"
tokio = { version = "1.45.1", features = ["full"] }
clap = { version = "4.5.40", features = ["derive", "env"] }
anyhow = "1.0.98"
rand = "0.9.1"
humantime = "2.2.0"
