[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
remappings = [
    "pod-sdk/=../../solidity-sdk/src/",
    "pod-protocol/=../../protocol/src",
    "pod-protocol-scripts/=../../protocol/script/",
    "optimistic-auction/=contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]
allow_paths = [
    "../../solidity-sdk",
    "../../protocol"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
exclude = ["lib/**"]