generate:
	forge bind --crate-name pod-examples-solidity --crate-version 0.2.0 --bindings-path ./bindings --alloy-version 1.0.24 --force --no-metadata --overwrite --skip script

check:
	forge bind --crate-name pod-examples-solidity --crate-version 0.2.0 --bindings-path ./bindings --alloy-version 1.0.24 --force --no-metadata --skip script
.PHONY: generate
.PHONY: check
