generate:
	forge bind --crate-name pod-examples-solidity --bindings-path ./bindings --alloy-version 1.0.9 --force --no-metadata --overwrite --skip script

check:
	forge bind --crate-name pod-examples-solidity --bindings-path ./bindings --alloy-version 1.0.9 --force --no-metadata --skip script
.PHONY: generate
.PHONY: check
