generate:
	forge bind --crate-name notary-bindings --bindings-path ./bindings --alloy-version 1.0.36 --force --no-metadata --overwrite --skip script

check:
	forge bind --crate-name notary-bindings --bindings-path ./bindings --alloy-version 1.0.36 --force --no-metadata --skip script
.PHONY: generate
.PHONY: check
