#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#auction;
pub mod r#fast_types;
pub mod r#pi2;
pub mod r#ranked_feed;
pub mod r#test_mint_balance_precompile;
pub mod r#time;
pub mod r#voting;
