# Deploy Doc Site
name: Deploy Doc Site
run-name: ${{ github.actor }} call deploy pod doc site 🚀
on:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  make-api-request:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_URL_MAIN: ${{ secrets.VERCEL_DEPLOY_URL_MAIN }}
    steps:
      # call Vercel API to deploy
      - name: Make API Request
        id: make-api-request
        run: |
          curl -X POST $VERCEL_DEPLOY_URL_MAIN -H "Content-Type: application/json" -H "Content-Length: 0" &
          wait

      - name: Echo response
        id: echo-response
        run: echo ${{ steps.make-api-request.outputs.response }}
