name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: install fmt for nightly
      run: rustup component add rustfmt --toolchain nightly

    - name: Version
      run: |
        cargo +nightly version
        cargo +nightly fmt --version

    - name: rustfmt check
      run: cargo +nightly fmt --check
